# Generated by Django 5.2.17 on 2026-09-26 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('signals_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.CharField(max_length=100, unique=True)),
                ('model_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=255)),
                ('training_timestamp', models.DateTimeField(auto_now_add=True)),
                ('dataset_size', models.IntegerField(default=0)),
                ('features', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('validation_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Model Version',
                'verbose_name_plural': 'Model Versions',
                'ordering': ['-training_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_green_seconds', models.IntegerField()),
                ('proposed_green_seconds', models.IntegerField()),
                ('simulation_duration_minutes', models.IntegerField(default=15)),
                ('connected_intersections', models.JSONField(blank=True, default=list)),
                ('baseline_metrics', models.JSONField(default=dict)),
                ('simulated_metrics', models.JSONField(default=dict)),
                ('delta_metrics', models.JSONField(default=dict)),
                ('network_impact', models.JSONField(default=dict)),
                ('data_sources', models.JSONField(default=dict)),
                ('ai_explanation', models.JSONField(default=dict)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='core.intersection')),
            ],
            options={
                'verbose_name': 'Simulation Result',
                'verbose_name_plural': 'Simulation Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('anomaly_type', models.CharField(default='UNUSUAL_SURGE', max_length=50)),
                ('confidence', models.FloatField(default=85.0)),
                ('supporting_metrics', models.JSONField(default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_anomalies', to='core.intersection')),
            ],
            options={
                'verbose_name': 'Traffic Anomaly',
                'verbose_name_plural': 'Traffic Anomalies',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficControlExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_green_seconds', models.IntegerField(default=45)),
                ('applied_green_seconds', models.IntegerField()),
                ('predicted_volume', models.FloatField(blank=True, null=True)),
                ('predicted_congestion', models.FloatField(blank=True, null=True)),
                ('predicted_queue', models.FloatField(blank=True, null=True)),
                ('predicted_delay', models.FloatField(blank=True, null=True)),
                ('actual_volume', models.FloatField(blank=True, null=True)),
                ('actual_congestion', models.FloatField(blank=True, null=True)),
                ('actual_queue', models.FloatField(blank=True, null=True)),
                ('actual_delay', models.FloatField(blank=True, null=True)),
                ('volume_error', models.FloatField(blank=True, null=True)),
                ('congestion_error', models.FloatField(blank=True, null=True)),
                ('queue_error', models.FloatField(blank=True, null=True)),
                ('delay_error', models.FloatField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('IMPROVED', 'Improved'), ('DEGRADED', 'Degraded'), ('NEUTRAL', 'Neutral')], default='IMPROVED', max_length=20)),
                ('was_congestion_reduced', models.BooleanField(default=True)),
                ('operator_notes', models.TextField(blank=True, default='')),
                ('used_in_retraining', models.BooleanField(default=False)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_experiences', to='core.intersection')),
            ],
            options={
                'verbose_name': 'Traffic Control Experience',
                'verbose_name_plural': 'Traffic Control Experiences',
                'ordering': ['-timestamp'],
            },
        ),
    ]
